<?php
declare(strict_types=1);
namespace AstronomyEngine\Facade;
use AstronomyEngine\LunarDayCalculator;use AstronomyEngine\MeeusLunarCalculator;use AstronomyEngine\MeeusSolarPositionCalculator;use AstronomyEngine\SolarDayCalculator;use DateTimeImmutable;use InvalidArgumentException;
final class AstronomyDirectionsFacade
{
    private readonly MeeusLunarCalculator $moon;private readonly MeeusSolarPositionCalculator $sun;private readonly LunarDayCalculator $lunarDay;private readonly SolarDayCalculator $solarDay;
    public function __construct(){$this->moon=new MeeusLunarCalculator();$this->sun=new MeeusSolarPositionCalculator();$this->lunarDay=new LunarDayCalculator($this->moon);$this->solarDay=new SolarDayCalculator($this->sun);}
    public function calculate(string $date,string $time,AstronomyObserver $observer):array{$localDate=FacadeSupport::localDate($date,$observer);$instant=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$date.' '.(strlen($time)===5?$time.':00':$time),$observer->timezone);$errors=DateTimeImmutable::getLastErrors();if(!$instant||($errors!==false&&($errors['warning_count']||$errors['error_count'])))throw new InvalidArgumentException('Time must use valid HH:MM or HH:MM:SS.');$sunDay=$this->solarDay->calculate($localDate,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$moonDay=$this->lunarDay->calculate($localDate,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$sun=$this->sun->calculate($instant,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$moon=$this->moon->calculate($instant,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);return['date'=>$date,'time'=>$instant->format('H:i:s'),'timezone'=>$observer->timezone->getName(),'observer'=>$observer->data(),'sun'=>['rise'=>$this->sunEvent($sunDay->sunrise,$observer),'set'=>$this->sunEvent($sunDay->sunset,$observer),'instant'=>['altitude_degrees'=>$sun->altitudeDegrees,'azimuth_degrees'=>$sun->azimuthDegrees,'above_horizon'=>$sun->altitudeDegrees>0]],'moon'=>['rise'=>$this->moonEvent($moonDay->moonrise,$observer),'set'=>$this->moonEvent($moonDay->moonset,$observer),'instant'=>['altitude_degrees'=>$moon->altitudeDegrees,'azimuth_degrees'=>$moon->azimuthDegrees,'above_horizon'=>$moon->altitudeDegrees>0]]];}
    private function sunEvent(?DateTimeImmutable $date,AstronomyObserver $o):?array{if(!$date)return null;$p=$this->sun->calculate($date,$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters);return['datetime'=>FacadeSupport::date($date),'time'=>$date->format('H:i:s'),'azimuth_degrees'=>$p->azimuthDegrees];}
    private function moonEvent(?DateTimeImmutable $date,AstronomyObserver $o):?array{if(!$date)return null;$p=$this->moon->calculate($date,$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters);return['datetime'=>FacadeSupport::date($date),'time'=>$date->format('H:i:s'),'azimuth_degrees'=>$p->azimuthDegrees];}
}
