<?php
declare(strict_types=1);
namespace AstronomyEngine\Facade;
use AstronomyEngine\LunarDayCalculator;use AstronomyEngine\MeeusLunarCalculator;use AstronomyEngine\MeeusSolarPositionCalculator;use AstronomyEngine\SolarDayCalculator;
final class DailyAstronomyFacade
{
    private const MOON_RADIUS_KM=1737.4;private const MEAN_DISTANCE_KM=384400.;private readonly MeeusLunarCalculator $moon;private readonly MeeusSolarPositionCalculator $sun;private readonly LunarDayCalculator $lunarDay;private readonly SolarDayCalculator $solarDay;
    public function __construct(){$this->moon=new MeeusLunarCalculator();$this->sun=new MeeusSolarPositionCalculator();$this->lunarDay=new LunarDayCalculator($this->moon);$this->solarDay=new SolarDayCalculator($this->sun);}
    public function calculate(string $date,AstronomyObserver $observer,bool $includeLightPeriods=false):array{$local=FacadeSupport::localDate($date,$observer);$noon=new \DateTimeImmutable($date.' 12:00:00',$observer->timezone);$moon=$this->moon->calculate($noon,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$lunarDay=$this->lunarDay->calculate($local,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$solarDay=$this->solarDay->calculate($local,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$sunIntervals=FacadeSupport::solarIntervals($solarDay,$local,$observer,$this->sun);$moonDiameter=2*atan(self::MOON_RADIUS_KM/$moon->topocentricDistanceKilometers);$meanDiameter=2*atan(self::MOON_RADIUS_KM/self::MEAN_DISTANCE_KM);$result=['date'=>$date,'calculation_time'=>FacadeSupport::date($noon),'location'=>$observer->data(),'moon'=>['phase'=>['name'=>$moon->phaseName,'angle_degrees'=>$moon->cycleAngleDegrees],'illumination_percent'=>$moon->illuminationFraction*100,'distance_km'=>$moon->topocentricDistanceKilometers,'distance_reference'=>'topocentric','apparent_size_percent'=>$moonDiameter/$meanDiameter*100,'age_days'=>$moon->ageDays,'rise'=>FacadeSupport::date($lunarDay->moonrise),'set'=>FacadeSupport::date($lunarDay->moonset),'visibility_intervals'=>FacadeSupport::lunarIntervals($lunarDay->visibilityIntervals)],'sun'=>['rise'=>FacadeSupport::date($solarDay->sunrise),'set'=>FacadeSupport::date($solarDay->sunset),'day_length_seconds'=>FacadeSupport::duration($sunIntervals),'visibility_intervals'=>$sunIntervals,'light_periods'=>null],'metadata'=>['calculation_model'=>'meeus-analytical','moon_mean_distance_km'=>self::MEAN_DISTANCE_KM,'rise_set_conventions'=>'astronomy-engine']];if($includeLightPeriods)$result['sun']['light_periods']=$this->lightPeriods($solarDay);return$result;}
    private function lightPeriods($day):array{return['solar_noon'=>FacadeSupport::date($day->solarNoon),'twilight'=>['morning'=>['astronomical'=>FacadeSupport::period($day->periods['morning_astronomical_twilight']),'nautical'=>FacadeSupport::period($day->periods['morning_nautical_twilight']),'civil'=>FacadeSupport::period($day->periods['morning_civil_twilight'])],'evening'=>['astronomical'=>FacadeSupport::period($day->periods['evening_astronomical_twilight']),'nautical'=>FacadeSupport::period($day->periods['evening_nautical_twilight']),'civil'=>FacadeSupport::period($day->periods['evening_civil_twilight'])]],'photographic'=>['definitions'=>['blue_hour_solar_altitude_degrees'=>[-6,-4],'golden_hour_solar_altitude_degrees'=>[-4,6]],'morning'=>['blue_hour'=>FacadeSupport::period($day->periods['morning_blue_hour']),'golden_hour'=>FacadeSupport::period($day->periods['morning_golden_hour'])],'evening'=>['golden_hour'=>FacadeSupport::period($day->periods['evening_golden_hour']),'blue_hour'=>FacadeSupport::period($day->periods['evening_blue_hour'])]]];}
}
