<?php
declare(strict_types=1);
namespace AstronomyEngine\Facade;
use AstronomyEngine\LunarDayCalculator;use AstronomyEngine\MeeusLunarCalculator;use AstronomyEngine\MeeusSolarPositionCalculator;use AstronomyEngine\PrincipalPhaseCalculator;use AstronomyEngine\PrecisionProfile;use AstronomyEngine\SolarDayCalculator;use DateTimeImmutable;use DateTimeZone;use InvalidArgumentException;
final class EarthshineFacade
{
    private const SAMPLE_MINUTES=15;private const MIN_ILLUMINATION=2.;private const MAX_ILLUMINATION=15.;private readonly PrincipalPhaseCalculator $phases;private readonly MeeusLunarCalculator $moon;private readonly MeeusSolarPositionCalculator $sun;private readonly LunarDayCalculator $lunarDays;private readonly SolarDayCalculator $solarDays;
    public function __construct(){$this->phases=new PrincipalPhaseCalculator();$this->moon=new MeeusLunarCalculator();$this->sun=new MeeusSolarPositionCalculator();$this->lunarDays=new LunarDayCalculator($this->moon);$this->solarDays=new SolarDayCalculator($this->sun);}
    public function between(DateTimeImmutable $start,DateTimeImmutable $end,AstronomyObserver $observer,int $sampleMinutes=self::SAMPLE_MINUTES):array
    {
        if($end<=$start)throw new InvalidArgumentException('End must be after start.');if($sampleMinutes<1)throw new InvalidArgumentException('Sample minutes must be positive.');$utc=new DateTimeZone('UTC');$startUtc=$start->setTimezone($utc);$endUtc=$end->setTimezone($utc);$opportunities=[];$windows=[];$phases=$this->phases->between($startUtc->modify('-3 days'),$endUtc->modify('+3 days'));
        foreach($phases as $phase){
            if($phase['type']!=='new_moon')continue;$newMoon=$phase['dateTime'];$base=$newMoon->setTimezone($observer->timezone);
            foreach([-2,-1,1,2] as $offset){
                $candidate=$base->modify(($offset>0?'+':'').$offset.' days');$local=FacadeSupport::localDate($candidate->format('Y-m-d'),$observer);$moonDay=$this->lunarDays->calculate($local,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$sunDay=$this->solarDays->calculate($local,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$morning=$offset<0;$moonEvent=$morning?$moonDay->moonrise:$moonDay->moonset;$solarEvent=$morning?$sunDay->sunrise:$sunDay->sunset;$usefulStart=$morning?$moonEvent:$solarEvent;$usefulEnd=$morning?$solarEvent:$moonEvent;$strict=$this->strictWindows($local,$newMoon,$offset,$startUtc,$endUtc,$observer,$sampleMinutes);foreach($strict as $window)$windows[]=$window;
                if(!$moonEvent||!$solarEvent||!$usefulStart||!$usefulEnd||$usefulEnd<=$usefulStart)continue;$clippedStart=max((float)$usefulStart->format('U.u'),(float)$startUtc->format('U.u'));$clippedEnd=min((float)$usefulEnd->format('U.u'),(float)$endUtc->format('U.u'));if($clippedEnd<=$clippedStart)continue;$best=$usefulStart->modify('+'.(int)round(((float)$usefulEnd->format('U.u')-(float)$usefulStart->format('U.u'))/2).' seconds');$p=$this->moon->calculate($best,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$matching=array_values(array_filter($strict,static fn($w)=>$w['offset_days']===$offset&&$w['new_moon_time']===FacadeSupport::date($newMoon)));
                $opportunities[]=['thin_moon_opportunity'=>true,'earthshine_visible'=>$matching!==[],'earthshine_window'=>$matching[0]??null,'earthshine_windows'=>$matching,'new_moon_time'=>FacadeSupport::date($newMoon),'candidate_date'=>$local->format('Y-m-d'),'offset_days'=>$offset,'period'=>$morning?'morning':'evening','start'=>FacadeSupport::date($this->date($clippedStart,$utc)),'end'=>FacadeSupport::date($this->date($clippedEnd,$utc)),'moon_event'=>$morning?'moonrise':'moonset','solar_event'=>$morning?'sunrise':'sunset','moon_event_time'=>FacadeSupport::date($moonEvent),'solar_event_time'=>FacadeSupport::date($solarEvent),'representative_time'=>FacadeSupport::date($best),'illumination_percent'=>$p->illuminationFraction*100,'separation_degrees'=>$this->elongation($p->cycleAngleDegrees),'location'=>$observer->data(),'calculation_model'=>'php-new-moon-local-opportunity-v1','precision_profile'=>PrecisionProfile::Normal->value];
            }
        }
        usort($opportunities,static fn($a,$b)=>strcmp($a['start'],$b['start']));usort($windows,static fn($a,$b)=>strcmp($a['start'],$b['start']));return['from'=>FacadeSupport::date($start),'to'=>FacadeSupport::date($end),'observer'=>$observer->data(),'sample_minutes'=>$sampleMinutes,'opportunities'=>$opportunities,'earthshine_windows'=>$windows];
    }
    private function strictWindows(DateTimeImmutable $local,DateTimeImmutable $newMoon,int $offset,DateTimeImmutable $rangeStart,DateTimeImmutable $rangeEnd,AstronomyObserver $o,int $minutes):array
    {
        $dayStart=new DateTimeImmutable($local->format('Y-m-d').' 00:00:00',$o->timezone);$dayEnd=$dayStart->modify('+1 day');$samples=[];
        for($time=$dayStart;$time<$dayEnd;$time=$time->modify("+{$minutes} minutes")){$moon=$this->moon->calculate($time,$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters);$sun=$this->sun->calculate($time,$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters);$illumination=$moon->illuminationFraction*100;$correctSide=$offset<0?$moon->cycleAngleDegrees>180:$moon->cycleAngleDegrees<180;$valid=$correctSide&&$illumination>=self::MIN_ILLUMINATION&&$illumination<=self::MAX_ILLUMINATION&&$moon->altitudeDegrees>0&&$sun->altitudeDegrees<-6;$samples[]=['time'=>$time,'valid'=>$valid,'illumination'=>$illumination,'moon_altitude'=>$moon->altitudeDegrees,'sun_altitude'=>$sun->altitudeDegrees,'separation'=>$this->elongation($moon->cycleAngleDegrees)];}
        $runs=[];for($i=0;$i<count($samples);){if(!$samples[$i]['valid']){$i++;continue;}$first=$i;while($i+1<count($samples)&&$samples[$i+1]['valid'])$i++;$last=$i;$rawStart=$samples[$first]['time'];$rawEnd=min($dayEnd,$samples[$last]['time']->modify("+{$minutes} minutes"));$start=max((float)$rawStart->format('U.u'),(float)$rangeStart->format('U.u'));$end=min((float)$rawEnd->format('U.u'),(float)$rangeEnd->format('U.u'));if($end>$start){$eligible=array_filter(array_slice($samples,$first,$last-$first+1),static fn($s)=>(float)$s['time']->format('U.u')>=$start&&(float)$s['time']->format('U.u')<$end);if($eligible!==[]){usort($eligible,static fn($a,$b)=>$b['moon_altitude']<=>$a['moon_altitude']);$best=$eligible[0];$runs[]=['start'=>FacadeSupport::date($this->date($start,new DateTimeZone('UTC'))),'end'=>FacadeSupport::date($this->date($end,new DateTimeZone('UTC'))),'duration_seconds'=>(int)round($end-$start),'representative_time'=>FacadeSupport::date($best['time']),'illumination_percent'=>$best['illumination'],'moon_altitude_degrees'=>$best['moon_altitude'],'sun_altitude_degrees'=>$best['sun_altitude'],'separation_degrees'=>$best['separation'],'period'=>$offset<0?'morning':'evening','offset_days'=>$offset,'new_moon_time'=>FacadeSupport::date($newMoon),'calculation_model'=>'15-minute-strict-earthshine-rules-v1'];}}$i++;}return$runs;
    }
    private function elongation(float $cycle):float{return min($cycle,360-$cycle);}private function date(float $ts,DateTimeZone $zone):DateTimeImmutable{return DateTimeImmutable::createFromFormat('U.u',sprintf('%.6F',$ts))->setTimezone($zone);}
}
