<?php
declare(strict_types=1);
namespace AstronomyEngine\Facade;
use AstronomyEngine\LunarDayCalculator;use AstronomyEngine\MeeusLunarCalculator;use AstronomyEngine\MeeusSolarPositionCalculator;use AstronomyEngine\PrincipalPhaseCalculator;use AstronomyEngine\PrecisionProfile;use AstronomyEngine\SolarDayCalculator;use DateTimeImmutable;use DateTimeZone;use InvalidArgumentException;
final class FullMoonObservationFacade
{
    private const MIN_ILLUMINATION_PERCENT=95.;private readonly PrincipalPhaseCalculator $phases;private readonly MeeusLunarCalculator $moon;private readonly LunarDayCalculator $lunarDays;private readonly SolarDayCalculator $solarDays;
    public function __construct(){$this->phases=new PrincipalPhaseCalculator();$this->moon=new MeeusLunarCalculator();$this->lunarDays=new LunarDayCalculator($this->moon);$this->solarDays=new SolarDayCalculator(new MeeusSolarPositionCalculator());}
    public function between(DateTimeImmutable $start,DateTimeImmutable $end,AstronomyObserver $observer,int $maxDifferenceMinutes=90):array{if($end<=$start)throw new InvalidArgumentException('End must be after start.');if($maxDifferenceMinutes<1||$maxDifferenceMinutes>180)throw new InvalidArgumentException('Maximum difference must be between 1 and 180 minutes.');$startUtc=$start->setTimezone(new DateTimeZone('UTC'));$endUtc=$end->setTimezone(new DateTimeZone('UTC'));$items=[];foreach($this->phases->between($startUtc,$endUtc) as $phase){if($phase['type']!=='full_moon')continue;$full=$phase['dateTime'];$base=$full->setTimezone($observer->timezone);foreach([-1,0,1] as $offset){$date=$base->modify(($offset>=0?'+':'').$offset.' days');$local=FacadeSupport::localDate($date->format('Y-m-d'),$observer);$moonDay=$this->lunarDays->calculate($local,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$sunDay=$this->solarDays->calculate($local,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);foreach([['evening',$moonDay->moonrise,$sunDay->sunset,'moonrise','sunset'],['morning',$moonDay->moonset,$sunDay->sunrise,'moonset','sunrise']] as [$period,$moonEvent,$solarEvent,$moonName,$solarName]){if(!$moonEvent||!$solarEvent)continue;$eventUtc=$moonEvent->setTimezone(new DateTimeZone('UTC'));if($eventUtc<$startUtc||$eventUtc>=$endUtc)continue;$difference=((float)$moonEvent->format('U.u')-(float)$solarEvent->format('U.u'))/60;if(abs(round($difference))>$maxDifferenceMinutes)continue;$position=$this->moon->calculate($moonEvent,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$illumination=$position->illuminationFraction*100;if($illumination<self::MIN_ILLUMINATION_PERCENT)continue;$items[]=['type'=>$period,'event_time'=>FacadeSupport::date($moonEvent),'full_moon_time'=>FacadeSupport::date($full),'candidate_date'=>$local->format('Y-m-d'),'offset_days'=>$offset,'moon_event'=>$moonName,'solar_event'=>$solarName,'moon_event_time'=>FacadeSupport::date($moonEvent),'solar_event_time'=>FacadeSupport::date($solarEvent),'difference_minutes'=>(int)round($difference),'illumination_percent'=>$illumination,'azimuth_degrees'=>$position->azimuthDegrees,'temporal_classification'=>$this->classification($solarName,$difference),'location'=>$observer->data(),'calculation_model'=>'php-phases-plus-local-days-v1','precision_profile'=>PrecisionProfile::Normal->value];}}}usort($items,static fn($a,$b)=>strcmp($a['event_time'],$b['event_time']));return['from'=>FacadeSupport::date($start),'to'=>FacadeSupport::date($end),'max_difference_minutes'=>$maxDifferenceMinutes,'observer'=>$observer->data(),'items'=>$items];}
    private function classification(string $solarEvent,float $differenceMinutes):string{return($differenceMinutes<0?'before':($differenceMinutes>0?'after':'at')).'_'.$solarEvent;}
}
