<?php
declare(strict_types=1);
namespace AstronomyEngine\Facade;
use AstronomyEngine\MeeusLunarCalculator;use DateTimeImmutable;use DateTimeZone;use InvalidArgumentException;
final readonly class MoonInstantFacade
{
    private const MOON_RADIUS_KM=1737.4;public function __construct(private MeeusLunarCalculator $moon=new MeeusLunarCalculator()){}
    public function calculate(DateTimeImmutable $instant,AstronomyObserver $observer):array{$utc=$instant->setTimezone(new DateTimeZone('UTC'));$local=$utc->setTimezone($observer->timezone);$p=$this->moon->calculate($utc,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$illumination=max(0,min(1,$p->illuminationFraction));$elongation=min($p->cycleAngleDegrees,360-$p->cycleAngleDegrees);$phaseAngle=rad2deg(acos(max(-1,min(1,2*$illumination-1))));return['body'=>'moon','datetime'=>['utc'=>FacadeSupport::date($utc),'local'=>FacadeSupport::date($local),'timezone'=>$observer->timezone->getName()],'phase'=>['name'=>$p->phaseName,'cycle_angle_degrees'=>$p->cycleAngleDegrees,'illumination_fraction'=>$illumination,'illumination_percent'=>$illumination*100,'age_days'=>$p->ageDays,'waxing'=>$p->cycleAngleDegrees<180],'observer'=>['latitude'=>$observer->latitudeDegrees,'longitude'=>$observer->longitudeDegrees,'altitude_degrees'=>$p->altitudeDegrees,'azimuth_degrees'=>$p->azimuthDegrees,'above_horizon'=>$p->altitudeDegrees>0,'position_reference'=>'topocentric','refraction'=>'none'],'distance'=>['kilometers'=>$p->distanceKilometers,'reference'=>'geocentric','topocentric_kilometers'=>$p->topocentricDistanceKilometers],'apparent_size'=>['angular_diameter_degrees'=>rad2deg(2*atan(self::MOON_RADIUS_KM/$p->distanceKilometers)),'distance_reference'=>'geocentric'],'coordinates'=>['right_ascension_hours'=>$p->rightAscensionDegrees/15,'declination_degrees'=>$p->declinationDegrees,'ecliptic_longitude_degrees'=>$p->eclipticLongitudeDegrees,'ecliptic_latitude_degrees'=>$p->eclipticLatitudeDegrees,'reference'=>'geocentric'],'geometry'=>['elongation_degrees'=>$elongation,'elongation_definition'=>'absolute ecliptic phase-cycle angle','phase_angle_degrees'=>$phaseAngle,'phase_angle_definition'=>'derived from illuminated fraction']];}
}
