<?php
declare(strict_types=1);
namespace AstronomyEngine;
use DateTimeImmutable;use DateTimeZone;use InvalidArgumentException;use RuntimeException;
/** Global lunar eclipses from analytical Sun/Moon positions and dynamic shadow geometry. */
final class LunarEclipseCalculator
{
    private const EARTH_RADIUS_KM=6378.14;private const MOON_RADIUS_KM=1737.1;private const SUN_RADIUS_KM=696340.0;private const DANJON_FACTOR=1.01;
    private readonly PrincipalPhaseCalculator $phases;private readonly MeeusEclipsePositionCalculator $positions;
    /** The optional argument preserves compatibility with the initial laboratory API. */public function __construct(?MeeusLunarCalculator $moon=null){$this->phases=new PrincipalPhaseCalculator();$this->positions=new MeeusEclipsePositionCalculator();}
    /** @return list<LunarEclipse> */public function events(DateTimeImmutable $start,DateTimeImmutable $end):array{$start=$start->setTimezone(new DateTimeZone('UTC'));$end=$end->setTimezone(new DateTimeZone('UTC'));if($end<=$start)throw new InvalidArgumentException('Eclipse interval end must be after start.');$events=[];$paddedStart=$start->modify('-2 days');$paddedEnd=$end->modify('+2 days');foreach($this->phases->between($paddedStart,$paddedEnd) as $phase){if($phase['type']!=='full_moon')continue;$center=(float)$phase['dateTime']->format('U.u');$maximum=$this->minimum($center-43200,$center+43200);$date=$this->date($maximum);if($date<$start||$date>=$end)continue;$geometry=$this->geometry($maximum);$classification=$this->classification($geometry);if($classification===null)continue;$contacts=$this->contacts($maximum,$classification);$moonDiameter=2*$geometry['moon_radius_radians'];$magnitudes=['umbral'=>($geometry['umbra_radius_radians']+$geometry['moon_radius_radians']-$geometry['closest_approach_radians'])/$moonDiameter,'penumbral'=>($geometry['penumbra_radius_radians']+$geometry['moon_radius_radians']-$geometry['closest_approach_radians'])/$moonDiameter];$durations=['penumbral'=>$this->duration($contacts->P1,$contacts->P4),'umbral'=>$contacts->U1&&$contacts->U4?$this->duration($contacts->U1,$contacts->U4):null,'total'=>$contacts->U2&&$contacts->U3?$this->duration($contacts->U2,$contacts->U3):null];$events[]=new LunarEclipse('eclipse','lunar_eclipse',$classification,$date,$contacts,$magnitudes,$durations,$geometry,'meeus-47-full-shadow-geometry-danjon-1.01-v2');}usort($events,static fn(LunarEclipse $a,LunarEclipse $b):int=>$a->maximum<=>$b->maximum);return$events;}
    /** Public render sample from the same shadow model used for contacts. */
    public function geometryAt(DateTimeImmutable $instant):array{return $this->geometry((float)$instant->setTimezone(new DateTimeZone('UTC'))->format('U.u'));}
    /** @return array<string,float> */private function geometry(float $time):array{$position=$this->positions->calculate($this->date($time));$moonLongitude=deg2rad($position['moon_longitude_degrees']);$moonLatitude=deg2rad($position['moon_latitude_degrees']);$sunLongitude=deg2rad($position['sun_longitude_degrees']);$separation=acos(max(-1,min(1,cos($moonLatitude)*cos($moonLongitude-$sunLongitude))));$closest=M_PI-$separation;$antiSun=$sunLongitude+M_PI;$longitudeOffset=atan2(sin($moonLongitude-$antiSun),cos($moonLongitude-$antiSun));$moonEast=cos($moonLatitude)*sin($longitudeOffset);$moonNorth=sin($moonLatitude);$moonDistance=$position['moon_distance_km'];$sunDistance=$position['sun_distance_km'];$moonRadius=asin(self::MOON_RADIUS_KM/$moonDistance);$piM=self::EARTH_RADIUS_KM/$moonDistance;$piS=self::EARTH_RADIUS_KM/$sunDistance;$sS=self::SUN_RADIUS_KM/$sunDistance;$pi1=self::DANJON_FACTOR*$piM;return['closest_approach_radians'=>$closest,'shadow_offset_east_radians'=>-$moonEast,'shadow_offset_north_radians'=>-$moonNorth,'moon_radius_radians'=>$moonRadius,'penumbra_radius_radians'=>$pi1+$piS+$sS,'umbra_radius_radians'=>$pi1+$piS-$sS];}
    private function classification(array $g):?string{if($g['closest_approach_radians']<$g['umbra_radius_radians']-$g['moon_radius_radians'])return'total';if($g['closest_approach_radians']<$g['umbra_radius_radians']+$g['moon_radius_radians'])return'partial';if($g['closest_approach_radians']<$g['penumbra_radius_radians']+$g['moon_radius_radians'])return'penumbral';return null;}
    private function contacts(float $maximum,string $type):LunarEclipseContacts{$p1=$this->contact($maximum,'P',true);$p4=$this->contact($maximum,'P',false);if($p1===null||$p4===null)throw new RuntimeException('Could not bracket penumbral eclipse contacts.');$u1=$u2=$u3=$u4=null;if($type!=='penumbral'){$u1=$this->contact($maximum,'U',true);$u4=$this->contact($maximum,'U',false);if($u1===null||$u4===null)throw new RuntimeException('Could not bracket umbral eclipse contacts.');}if($type==='total'){$u2=$this->contact($maximum,'T',true);$u3=$this->contact($maximum,'T',false);if($u2===null||$u3===null)throw new RuntimeException('Could not bracket total eclipse contacts.');}return new LunarEclipseContacts($this->date($p1),$u1===null?null:$this->date($u1),$u2===null?null:$this->date($u2),$this->date($maximum),$u3===null?null:$this->date($u3),$u4===null?null:$this->date($u4),$this->date($p4));}
    private function contact(float $maximum,string $kind,bool $before):?float{$inside=$maximum;$insideValue=$this->contactValue($inside,$kind);if($insideValue>0)return null;$direction=$before?-1:1;for($i=1;$i<=240;$i++){$candidate=$maximum+$direction*$i*120;$value=$this->contactValue($candidate,$kind);if($value>0){$left=min($inside,$candidate);$right=max($inside,$candidate);return$this->bisect($left,$right,fn(float $t):float=>$this->contactValue($t,$kind));}$inside=$candidate;}return null;}
    private function contactValue(float $time,string $kind):float{$g=$this->geometry($time);$threshold=match($kind){'P'=>$g['penumbra_radius_radians']+$g['moon_radius_radians'],'U'=>$g['umbra_radius_radians']+$g['moon_radius_radians'],'T'=>$g['umbra_radius_radians']-$g['moon_radius_radians']};return$g['closest_approach_radians']-$threshold;}
    private function minimum(float $a,float $b):float{$ratio=(sqrt(5)-1)/2;$c=$b-$ratio*($b-$a);$d=$a+$ratio*($b-$a);for($i=0;$i<32;$i++){$fc=$this->geometry($c)['closest_approach_radians'];$fd=$this->geometry($d)['closest_approach_radians'];if($fc<$fd){$b=$d;$d=$c;$c=$b-$ratio*($b-$a);}else{$a=$c;$c=$d;$d=$a+$ratio*($b-$a);}}return($a+$b)/2;}
    private function bisect(float $a,float $b,callable $fn):float{$fa=$fn($a);for($i=0;$i<60&&$b-$a>.25;$i++){$m=($a+$b)/2;$fm=$fn($m);if(($fa<=0&&$fm>=0)||($fa>=0&&$fm<=0))$b=$m;else{$a=$m;$fa=$fm;}}return($a+$b)/2;}
    private function duration(DateTimeImmutable $a,DateTimeImmutable $b):int{return(int)round((float)$b->format('U.u')-(float)$a->format('U.u'));}private function date(float $seconds):DateTimeImmutable{return DateTimeImmutable::createFromFormat('U.u',sprintf('%.6F',$seconds),new DateTimeZone('UTC'))->setTimezone(new DateTimeZone('UTC'));}
}
