<?php
declare(strict_types=1);
namespace AstronomyEngine;
use DateTimeImmutable;
final class LunarEclipseLocalCalculator
{
    private readonly MeeusLunarCalculator $moon;private readonly EclipseTopocentricGeometry $geometry;private readonly LunarDayCalculator $days;
    public function __construct(){$this->moon=new MeeusLunarCalculator();$this->geometry=new EclipseTopocentricGeometry();$this->days=new LunarDayCalculator($this->moon);}
    public function calculate(LunarEclipse $eclipse,EclipseObserver $observer):LunarEclipseLocalCircumstances{$contacts=[];$visible=[];foreach($eclipse->contacts->all() as $code=>$time){if($time===null)continue;$p=$this->moon->calculate($time,$observer->latitudeDegrees,$observer->longitudeDegrees,$observer->elevationMeters);$radius=rad2deg(asin(1737.4/$p->topocentricDistanceKilometers));$isVisible=$p->altitudeDegrees>=-(34/60)-$radius;$contacts[$code]=$this->contact($code,$time,$p->altitudeDegrees,$p->azimuthDegrees,$isVisible,$observer);if($isVisible)$visible[]=$code;}$start=$eclipse->contacts->P1;$end=$eclipse->contacts->P4;[$rise,$set,$interval]=$this->visibilityWindow($start,$end,$observer);$isVisible=$interval!==null;$all=array_keys($contacts);$visibilityClass=!$isVisible?'not_visible':(count($visible)===count($all)&&$rise===null&&$set===null?'fully_visible':'partially_visible');$max=$contacts['MAX']??[];return new LunarEclipseLocalCircumstances($isVisible,$visibilityClass,$contacts,$visible,$rise,$set,$interval,$max,$observer->timezone->getName(),$observer->data(),'meeus-topocentric-lunar-contacts-and-day-horizon-v1');}
    private function visibilityWindow(DateTimeImmutable $start,DateTimeImmutable $end,EclipseObserver $o):array{$cursor=new DateTimeImmutable($start->setTimezone($o->timezone)->format('Y-m-d').' 00:00:00',$o->timezone);$last=new DateTimeImmutable($end->setTimezone($o->timezone)->format('Y-m-d').' 00:00:00',$o->timezone);$rise=$set=null;$first=$final=null;while($cursor<=$last){$day=$this->days->calculate($cursor,$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters);if($day->moonrise&&$day->moonrise>$start&&$day->moonrise<$end)$rise=$day->moonrise;if($day->moonset&&$day->moonset>$start&&$day->moonset<$end)$set=$day->moonset;foreach($day->visibilityIntervals as $v){$a=max((float)$start->format('U.u'),(float)$v->start->format('U.u'));$b=min((float)$end->format('U.u'),(float)$v->end->format('U.u'));if($b>$a){$first=$first===null?$a:min($first,$a);$final=$final===null?$b:max($final,$b);}}$cursor=$cursor->modify('+1 day');}return[$rise,$set,$first===null?null:['start'=>$this->date($first,$o),'end'=>$this->date($final,$o)]];}
    private function contact(string $code,DateTimeImmutable $utc,float $alt,float $az,bool $visible,EclipseObserver $o):array{return['code'=>$code,'utc'=>$utc->setTimezone(new \DateTimeZone('UTC')),'local'=>$utc->setTimezone($o->timezone),'altitude_degrees'=>$alt,'azimuth_degrees'=>$az,'visible'=>$visible];}
    private function date(float $ts,EclipseObserver $o):DateTimeImmutable{return DateTimeImmutable::createFromFormat('U.u',sprintf('%.6F',$ts))->setTimezone($o->timezone);}
}
