<?php
declare(strict_types=1);
namespace AstronomyEngine;
use DateTimeImmutable;use DateTimeZone;
/** Topocentric apparent-disk contacts using standard Meeus vector parallax. */
final class SolarEclipseLocalCalculator
{
    private const SEARCH_SECONDS=21600.;private const SAMPLE_SECONDS=120.;
    private readonly EclipseTopocentricGeometry $geometry;private readonly MeeusSolarPositionCalculator $sun;private readonly SolarDayCalculator $days;
    public function __construct(){$this->geometry=new EclipseTopocentricGeometry();$this->sun=new MeeusSolarPositionCalculator();$this->days=new SolarDayCalculator($this->sun);}
    /** Public render sample from the same topocentric apparent-disk model used for local contacts. */
    public function geometrySample(DateTimeImmutable $instant,EclipseObserver $observer):array
    {
        $raw=$this->geometry->calculate($instant,$observer);$g=$this->geometryAt((float)$instant->setTimezone(new DateTimeZone('UTC'))->format('U.u'),$observer);
        $sun=$raw['sun']['unit'];$moon=$raw['moon']['unit'];$ra=atan2($sun[1],$sun[0]);$dec=asin(max(-1.,min(1.,$sun[2])));
        $north=[-cos($ra)*sin($dec),-sin($ra)*sin($dec),cos($dec)];$east=[-sin($ra),cos($ra),0.];
        $delta=[$moon[0]-$sun[0],$moon[1]-$sun[1],$moon[2]-$sun[2]];
        $northOffset=$delta[0]*$north[0]+$delta[1]*$north[1]+$delta[2]*$north[2];$eastOffset=$delta[0]*$east[0]+$delta[1]*$east[1]+$delta[2]*$east[2];
        $phi=deg2rad($observer->latitudeDegrees);$alt=deg2rad($g['sun_altitude']);$az=deg2rad($g['sun_azimuth']);
        $celestialNorth=rad2deg(atan2(-cos($phi)*sin($az),-cos($phi)*sin($alt)*cos($az)+sin($phi)*cos($alt)));
        return $g+['datetime_utc'=>$instant->setTimezone(new DateTimeZone('UTC')),'offset_east_radians'=>$eastOffset,'offset_north_radians'=>$northOffset,'position_angle_degrees'=>rad2deg(atan2($eastOffset,$northOffset)),'celestial_north_screen_angle_degrees'=>$celestialNorth];
    }
    public function calculate(SolarEclipse $eclipse,EclipseObserver $observer):SolarEclipseLocalCircumstances{$center=(float)$eclipse->maximum->format('U.u');$maximum=$this->minimum($center-self::SEARCH_SECONDS,$center+self::SEARCH_SECONDS,$observer);$g=$this->geometryAt($maximum,$observer);if($g['external']>=0)return new SolarEclipseLocalCircumstances(false,null,[],[],null,null,null,null,null,null,$this->maximumData($maximum,$g,$observer),$observer->timezone->getName(),$observer->data(),'meeus-topocentric-apparent-disks-v1');$external=$this->roots($maximum,'external',$observer);if(count($external)<2)return new SolarEclipseLocalCircumstances(false,null,[],[],null,null,null,null,null,null,$this->maximumData($maximum,$g,$observer),$observer->timezone->getName(),$observer->data(),'meeus-topocentric-apparent-disks-v1');[$c1,$c4]=[$external[0],$external[count($external)-1]];$central=$g['internal']<0;$classification=$central?($g['moon_radius']>=$g['sun_radius']?'total':'annular'):'partial';$internal=$central?$this->roots($maximum,'internal',$observer):[];$times=['C1'=>$c1];if(count($internal)>=2)$times['C2']=$internal[0];$times['MAX']=$maximum;if(count($internal)>=2)$times['C3']=$internal[count($internal)-1];$times['C4']=$c4;$contacts=[];$visible=[];foreach($times as $code=>$time){$geo=$this->geometryAt($time,$observer);$isVisible=$geo['sun_altitude']>=SolarDayCalculator::SUN_HORIZON_DEGREES;$contacts[$code]=$this->contact($code,$time,$geo,$isVisible,$observer);if($isVisible)$visible[]=$code;}[$sunrise,$sunset,$interval]=$this->visibilityWindow($c1,$c4,$observer);$visibleEvent=$interval!==null;$magnitude=max(0,($g['moon_radius']+$g['sun_radius']-$g['separation'])/(2*$g['sun_radius']));$obscuration=$this->overlap($g['sun_radius'],$g['moon_radius'],$g['separation']);$duration=count($internal)>=2?(int)round($internal[count($internal)-1]-$internal[0]):null;return new SolarEclipseLocalCircumstances($visibleEvent,$visibleEvent?$classification:null,$contacts,$visible,$sunrise,$sunset,$interval,$magnitude,$obscuration,$duration,$this->maximumData($maximum,$g,$observer),$observer->timezone->getName(),$observer->data(),'meeus-topocentric-apparent-disks-v1');}
    private function geometryAt(float $time,EclipseObserver $o):array{$g=$this->geometry->calculate($this->date($time,new DateTimeZone('UTC')),$o);$sep=$g['separation_radians'];$mr=$g['moon']['angular_radius_radians'];$sr=$g['sun']['angular_radius_radians'];return['separation'=>$sep,'moon_radius'=>$mr,'sun_radius'=>$sr,'external'=>$sep-$mr-$sr,'internal'=>$sep-abs($mr-$sr),'sun_altitude'=>$g['sun']['altitude_degrees'],'sun_azimuth'=>$g['sun']['azimuth_degrees'],'moon_altitude'=>$g['moon']['altitude_degrees'],'moon_azimuth'=>$g['moon']['azimuth_degrees']];}
    private function minimum(float $a,float $b,EclipseObserver $o):float{$r=(sqrt(5)-1)/2;$c=$b-$r*($b-$a);$d=$a+$r*($b-$a);for($i=0;$i<38;$i++){if($this->geometryAt($c,$o)['separation']<$this->geometryAt($d,$o)['separation']){$b=$d;$d=$c;$c=$b-$r*($b-$a);}else{$a=$c;$c=$d;$d=$a+$r*($b-$a);}}return($a+$b)/2;}
    private function roots(float $maximum,string $field,EclipseObserver $o):array{$roots=[];$start=$maximum-self::SEARCH_SECONDS;$previous=$start;$pv=$this->geometryAt($previous,$o)[$field];for($time=$start+self::SAMPLE_SECONDS;$time<=$maximum+self::SEARCH_SECONDS;$time+=self::SAMPLE_SECONDS){$v=$this->geometryAt($time,$o)[$field];if(($pv<0&&$v>=0)||($pv>=0&&$v<0))$roots[]=$this->bisect($previous,$time,$field,$o);$previous=$time;$pv=$v;}return$roots;}
    private function bisect(float $a,float $b,string $field,EclipseObserver $o):float{$av=$this->geometryAt($a,$o)[$field];while($b-$a>.1){$m=($a+$b)/2;$mv=$this->geometryAt($m,$o)[$field];if(($av<0)===($mv<0)){$a=$m;$av=$mv;}else$b=$m;}return($a+$b)/2;}
    private function visibilityWindow(float $start,float $end,EclipseObserver $o):array{$local=$this->date($start,$o->timezone);$cursor=new DateTimeImmutable($local->format('Y-m-d').' 00:00:00',$o->timezone);$last=$this->date($end,$o->timezone);$last=new DateTimeImmutable($last->format('Y-m-d').' 00:00:00',$o->timezone);$crossings=[];$sunrise=$sunset=null;while($cursor<=$last){$day=$this->days->calculate($cursor,$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters);foreach([['rise',$day->sunrise],['set',$day->sunset]] as [$kind,$date])if($date){$ts=(float)$date->format('U.u');if($ts>$start&&$ts<$end){$crossings[]=$ts;if($kind==='rise')$sunrise=$date;else$sunset=$date;}}$cursor=$cursor->modify('+1 day');}$points=array_merge([$start],$crossings,[$end]);sort($points);$first=$final=null;for($i=0;$i<count($points)-1;$i++){$a=$points[$i];$b=$points[$i+1];$alt=$this->sun->calculate($this->date(($a+$b)/2,new DateTimeZone('UTC')),$o->latitudeDegrees,$o->longitudeDegrees,$o->elevationMeters)->altitudeDegrees;if($alt>=SolarDayCalculator::SUN_HORIZON_DEGREES){$first=$first===null?$a:min($first,$a);$final=$final===null?$b:max($final,$b);}}return[$sunrise,$sunset,$first===null?null:['start'=>$this->date($first,$o->timezone),'end'=>$this->date($final,$o->timezone)]];}
    private function overlap(float $r,float $R,float $d):float{if($d>=$r+$R)return 0.;if($d<=abs($r-$R))return $R>=$r?1.:($R*$R)/($r*$r);$a=acos(max(-1,min(1,($d*$d+$r*$r-$R*$R)/(2*$d*$r))));$b=acos(max(-1,min(1,($d*$d+$R*$R-$r*$r)/(2*$d*$R))));$area=$r*$r*$a+$R*$R*$b-.5*sqrt(max(0,(-$d+$r+$R)*($d+$r-$R)*($d-$r+$R)*($d+$r+$R)));return$area/(M_PI*$r*$r);}
    private function contact(string $code,float $time,array $g,bool $visible,EclipseObserver $o):array{$utc=$this->date($time,new DateTimeZone('UTC'));return['code'=>$code,'utc'=>$utc,'local'=>$utc->setTimezone($o->timezone),'altitude_degrees'=>$g['sun_altitude'],'azimuth_degrees'=>$g['sun_azimuth'],'visible'=>$visible];}
    private function maximumData(float $time,array $g,EclipseObserver $o):array{return['utc'=>$this->date($time,new DateTimeZone('UTC')),'local'=>$this->date($time,$o->timezone),'separation_radians'=>$g['separation'],'sun_radius_radians'=>$g['sun_radius'],'moon_radius_radians'=>$g['moon_radius'],'altitude_degrees'=>$g['sun_altitude'],'azimuth_degrees'=>$g['sun_azimuth']];}
    private function date(float $ts,DateTimeZone $zone):DateTimeImmutable{return DateTimeImmutable::createFromFormat('U.u',sprintf('%.6F',$ts))->setTimezone($zone);}
}
