#!/usr/bin/env bash
set -euo pipefail

base_url="${1:-http://127.0.0.1:18080}"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

docker exec web-astro php /var/www/html/scripts/migrations/create-lunar-scene-presets.php >/dev/null

preset_api_status="$(curl -sS -o "$work_dir/presets-unauth" -w '%{http_code}' "$base_url/admin/api/lunar-scene-presets.php")"
test "$preset_api_status" = "401"

curl -fsS "$base_url/embeds/libracion-lunar.php?mode=full&autoplay=0&speed=2&controls=0" -o "$work_dir/libration"
grep -q 'data-libration-widget' "$work_dir/libration"
grep -q '"illumination":"full"' "$work_dir/libration"
grep -q '"autoplay":false' "$work_dir/libration"
grep -q '"speed":2' "$work_dir/libration"
grep -q '"wallpaper":{' "$work_dir/libration"
grep -q '"background_color":' "$work_dir/libration"
! grep -q 'data-libration-toggle' "$work_dir/libration"

curl -fsS "$base_url/embeds/luna-interactiva.php?yaw=45&pitch=-10&zoom=1.2&craters=1&maria=0&landings=1&detail=more&rotation=locked&controls=0" -o "$work_dir/interactive"
grep -q 'data-interactive-moon' "$work_dir/interactive"
grep -q 'is-rotation-locked' "$work_dir/interactive"
grep -q '"yaw":45' "$work_dir/interactive"
grep -q '"zoom":1.2' "$work_dir/interactive"
! grep -q 'lunar-widget__toolbar' "$work_dir/interactive"

curl -fsS "$base_url/embeds/fases-tierra-luna.php?fecha=2026-08-17&hora=12:00&autoplay=1&speed=2&controls=0&moon_sun=4.1&moon_normal_y=-2&earth_ambient=0.2&earth_roughness=0.75" -o "$work_dir/earth-moon"
grep -q 'data-earth-moon-widget' "$work_dir/earth-moon"

curl -fsS "$base_url/embeds/lunas-llenas-tamano.php?date=2026-09-06&controls=0" -o "$work_dir/full-moon-sizes"
grep -q 'data-full-moon-sizes' "$work_dir/full-moon-sizes"
grep -q '100 % = diámetro aparente a la distancia lunar media (384.400 km)' "$work_dir/full-moon-sizes"
test "$(grep -o 'class="full-moon-sizes__item"' "$work_dir/full-moon-sizes" | wc -l)" = "12"
test "$(grep -o 'class="full-moon-sizes__reference"' "$work_dir/full-moon-sizes" | wc -l)" = "12"
grep -q -- '--size-scale:' "$work_dir/full-moon-sizes"
! grep -q 'full-moon-sizes__controls' "$work_dir/full-moon-sizes"
grep -q 'noindex,nofollow,noarchive' "$work_dir/full-moon-sizes"
! grep -q '<nav' "$work_dir/full-moon-sizes"

curl -fsS "$base_url/embeds/escena-lunar.php?fecha=2026-09-20&hora=18%3A45&location_mode=active&lit_brightness=4.2&lit_tint=%23ffd4a3&dark_brightness=0.12&texture_saturation=1.3&texture_contrast=1.4&texture_resolution=low&earthshine_intensity=0.28&shadow_sky_mix=0.35&dark_side_opacity=0.62&dark_limb_softness=0.14&halo_intensity=0.42&edge_softness=0.035&terminator_softness=0.21&sky_mode=custom&sky_center_color=%23315b88&sky_center_brightness=1.2&sky_edge_color=%23182840&sky_edge_brightness=0.5&sky_gradient_radius=72" -o "$work_dir/lunar-scene"
grep -q 'data-lunar-scene' "$work_dir/lunar-scene"
grep -q 'data-moon-three' "$work_dir/lunar-scene"
grep -q 'noindex,nofollow,noarchive' "$work_dir/lunar-scene"
grep -q '2026-09-20T18:45:00-03:00' "$work_dir/lunar-scene"
grep -q 'ldem_3_normal' "$work_dir/lunar-scene"
grep -q -- '--lunar-scene-center: #3b6da3' "$work_dir/lunar-scene"
grep -q -- '--lunar-scene-edge: #0c1420' "$work_dir/lunar-scene"
grep -q -- '--lunar-scene-radius: 72.00%' "$work_dir/lunar-scene"
grep -q -- '--lunar-scene-halo: 0.420' "$work_dir/lunar-scene"
grep -q '"earthshine_intensity":0.28' "$work_dir/lunar-scene"
grep -q '"shadow_sky_mix":0.35' "$work_dir/lunar-scene"
grep -q '"dark_side_opacity":0.62' "$work_dir/lunar-scene"
grep -q '"dark_limb_softness":0.14' "$work_dir/lunar-scene"
grep -q '"edge_softness":0.035' "$work_dir/lunar-scene"
grep -q '"terminator_softness":0.21' "$work_dir/lunar-scene"
grep -q '"lit_tint":"#ffd4a3"' "$work_dir/lunar-scene"
! grep -q '<nav' "$work_dir/lunar-scene"
! grep -q '<form' "$work_dir/lunar-scene"

curl -fsS "$base_url/embeds/eclipse-lunar.php?autoplay=0&speed=2&controls=1&geometry=1&sun_intensity=4.2&ambient_intensity=0.03&exposure=1.3&penumbra_darkness=0.25&umbra_darkness=0.92&copper_intensity=0.4&copper_color=%23a04f31" -o "$work_dir/eclipse"
grep -q 'noindex,nofollow,noarchive' "$work_dir/eclipse"
grep -q 'data-lunar-eclipse-widget' "$work_dir/eclipse"
grep -q 'Eclipse lunar total del 3 de marzo de 2026' "$work_dir/eclipse"
grep -q '"sun_intensity":4.2' "$work_dir/eclipse"
grep -q '"copper_color":"#a04f31"' "$work_dir/eclipse"
curl -fsS "$base_url/embeds/eclipse-lunar-real.php?date=2026-03-03&lat=-34.6037&lon=-58.3816&autoplay=0&totality_brightness=1.2&totality_copper_intensity=1.4&totality_max_darkness=0.91&totality_gradient_contrast=1.5&totality_edge_color=%23d98b45&totality_deep_color=%235a120e&totality_saturation=1.2&totality_texture_contrast=0.5&totality_gradient_softness=0.2&totality_atmospheric_irregularity=0" -o "$work_dir/real-lunar-eclipse"
grep -q 'data-real-lunar-eclipse' "$work_dir/real-lunar-eclipse"
grep -q '"classification":"total"' "$work_dir/real-lunar-eclipse"
grep -q '"timezone":"America/Argentina/Buenos_Aires"' "$work_dir/real-lunar-eclipse"
grep -q '"totality_brightness":1.2' "$work_dir/real-lunar-eclipse"
grep -q '"totality_copper_intensity":1.4' "$work_dir/real-lunar-eclipse"
grep -q '"totality_max_darkness":0.91' "$work_dir/real-lunar-eclipse"
grep -q '"totality_gradient_contrast":1.5' "$work_dir/real-lunar-eclipse"
grep -q '"totality_atmospheric_irregularity":0' "$work_dir/real-lunar-eclipse"
curl -fsS "$base_url/embeds/eclipse-solar-real.php?date=2026-08-12&lat=43.3623&lon=-8.4115&autoplay=0&corona_level=8&prominence_level=3&baily_level=5&exposure=1.25&sun_intensity=1.1&limb_darkening=0.08&sky_brightness=0.9&corona_brightness=1.2&prominence_intensity=0.8&baily_intensity=1.4" -o "$work_dir/real-solar-eclipse"
grep -q 'data-real-solar-eclipse' "$work_dir/real-solar-eclipse"
grep -q 'Nunca observes el Sol directamente' "$work_dir/real-solar-eclipse"
grep -q '"local_classification":"total"' "$work_dir/real-solar-eclipse"
grep -q '"corona_level":8' "$work_dir/real-solar-eclipse"
grep -q '"prominence_level":3' "$work_dir/real-solar-eclipse"
grep -q '"baily_level":5' "$work_dir/real-solar-eclipse"
grep -q '"exposure":1.25' "$work_dir/real-solar-eclipse"
grep -q '"sun_intensity":1.1' "$work_dir/real-solar-eclipse"
grep -q '"corona_intensity":1.2' "$work_dir/real-solar-eclipse"
grep -q '"baily_intensity":1.4' "$work_dir/real-solar-eclipse"

curl -fsS "$base_url/embeds/eclipse-solar-espacio.php?date=2026-08-12&autoplay=0&show_moon=1&penumbra_opacity=0.31&core_opacity=0.72&distance_scale=4.2&follow_shadow=1" -o "$work_dir/solar-space-eclipse"
grep -q 'data-solar-space-eclipse' "$work_dir/solar-space-eclipse"
grep -q 'Distancias no a escala' "$work_dir/solar-space-eclipse"
grep -q '"classification":"total"' "$work_dir/solar-space-eclipse"
grep -q '"penumbra_opacity":0.31' "$work_dir/solar-space-eclipse"
grep -q '"distance_scale":4.2' "$work_dir/solar-space-eclipse"
grep -q '"follow_shadow":true' "$work_dir/solar-space-eclipse"
grep -q 'Fases Tierra–Luna' "$work_dir/earth-moon"
grep -q 'noindex,nofollow,noarchive' "$work_dir/earth-moon"
grep -q '"selected_datetime":"2026-08-17T12:00:00-03:00"' "$work_dir/earth-moon"
grep -q '"autoplay":true' "$work_dir/earth-moon"
grep -q '"speed":2' "$work_dir/earth-moon"
grep -q '"moon_sun":4.1' "$work_dir/earth-moon"
grep -q '"moon_normal_y":-2' "$work_dir/earth-moon"
grep -q '"earth_ambient":0.2' "$work_dir/earth-moon"
grep -q '"earth_roughness":0.75' "$work_dir/earth-moon"
! grep -q 'data-earth-moon-toggle' "$work_dir/earth-moon"
! grep -q '<nav' "$work_dir/earth-moon"
curl -fsS "$base_url/sitemap.xml" -o "$work_dir/sitemap"
! grep -q 'fases-tierra-luna' "$work_dir/sitemap"
! grep -q 'eclipse-lunar' "$work_dir/sitemap"
! grep -q 'eclipse-solar-real' "$work_dir/sitemap"
! grep -q 'lunas-llenas-tamano' "$work_dir/sitemap"
! grep -q 'escena-lunar' "$work_dir/sitemap"

status="$(curl -sS -o "$work_dir/admin-unauth" -D "$work_dir/admin-headers" -w '%{http_code}' "$base_url/admin/widgets-lunares/")"
test "$status" = "303"
grep -Eqi '^Location: \../login\.php' "$work_dir/admin-headers"
session_id="$(docker exec -i --user www-data web-astro php -r 'require "/var/www/html/includes/store-admin-auth.php"; session_id("lunar-widgets-http-" . bin2hex(random_bytes(12))); startStoreAdminSession(); $_SESSION[STORE_ADMIN_SESSION_KEY] = true; session_write_close(); echo session_id();')"
curl -fsS -H "Cookie: aquellas_lunas_admin=$session_id" "$base_url/admin/widgets-lunares/" -o "$work_dir/admin"
curl -fsS -H "Cookie: aquellas_lunas_admin=$session_id" "$base_url/admin/api/lunar-scene-presets.php" -o "$work_dir/presets"
grep -q '"presets"' "$work_dir/presets"
csrf_token="$(sed -n 's/.*data-csrf-token="\([a-f0-9]*\)".*/\1/p' "$work_dir/admin" | head -1)"
test -n "$csrf_token"
preset_configuration='{"fecha":"2026-09-12","hora":"06:25","location_mode":"active","lit_brightness":"4.1","lit_tint":"#ffd4a3","dark_brightness":"0.08","texture_saturation":"1.1","texture_contrast":"1.25","texture_resolution":"high","earthshine_intensity":"0.32","shadow_sky_mix":"0.48","dark_side_opacity":"0.66","dark_limb_softness":"0.12","halo_intensity":"0.22","edge_softness":"0.03","terminator_softness":"0.2","sky_mode":"custom","sky_center_color":"#91b7d4","sky_center_brightness":"1.1","sky_edge_color":"#496a8a","sky_edge_brightness":"0.9","sky_gradient_radius":"74"}'
curl -fsS -H "Cookie: aquellas_lunas_admin=$session_id" -X POST "$base_url/admin/api/lunar-scene-presets.php" --data-urlencode "csrf_token=$csrf_token" --data-urlencode 'action=create' --data-urlencode 'name=Preset HTTP temporal' --data-urlencode 'description=Prueba recuperable' --data-urlencode "configuration=$preset_configuration" -o "$work_dir/preset-create"
created_preset_id="$(sed -n 's/.*"preset":{"id":\([0-9]*\).*/\1/p' "$work_dir/preset-create")"
test -n "$created_preset_id"
curl -fsS -H "Cookie: aquellas_lunas_admin=$session_id" -X POST "$base_url/admin/api/lunar-scene-presets.php" --data-urlencode "csrf_token=$csrf_token" --data-urlencode 'action=update' --data-urlencode "id=$created_preset_id" --data-urlencode 'name=Preset HTTP actualizado' --data-urlencode 'description=' --data-urlencode "configuration=$preset_configuration" -o "$work_dir/preset-update"
grep -q 'Preset HTTP actualizado' "$work_dir/preset-update"
curl -fsS -H "Cookie: aquellas_lunas_admin=$session_id" -X POST "$base_url/admin/api/lunar-scene-presets.php" --data-urlencode "csrf_token=$csrf_token" --data-urlencode 'action=duplicate' --data-urlencode "id=$created_preset_id" -o "$work_dir/preset-duplicate"
duplicated_preset_id="$(sed -n 's/.*"preset":{"id":\([0-9]*\).*/\1/p' "$work_dir/preset-duplicate")"
test -n "$duplicated_preset_id"
for preset_id in "$created_preset_id" "$duplicated_preset_id"; do
    curl -fsS -H "Cookie: aquellas_lunas_admin=$session_id" -X POST "$base_url/admin/api/lunar-scene-presets.php" --data-urlencode "csrf_token=$csrf_token" --data-urlencode 'action=delete' --data-urlencode "id=$preset_id" -o "$work_dir/preset-delete-$preset_id"
done
grep -q '<h1>Widgets lunares</h1>' "$work_dir/admin"
grep -q 'data-widget-preview' "$work_dir/admin"
grep -q 'data-widget-url' "$work_dir/admin"
! grep -q 'readonly data-widget-url' "$work_dir/admin"
grep -q 'También podés pegar una URL de cualquiera de los widgets' "$work_dir/admin"
grep -q 'data-widget-iframe' "$work_dir/admin"
grep -q 'data-widget-options="earth-moon"' "$work_dir/admin"
grep -q 'data-widget-options="full-moon-sizes"' "$work_dir/admin"
grep -q 'data-widget-options="lunar-scene"' "$work_dir/admin"
grep -q 'data-lunar-scene-presets' "$work_dir/admin"
grep -q 'data-preset-action="create"' "$work_dir/admin"
grep -q 'data-preset-action="update"' "$work_dir/admin"
grep -q 'data-preset-action="duplicate"' "$work_dir/admin"
grep -q 'data-preset-action="delete"' "$work_dir/admin"
grep -q 'href="../widgets-lunares/" aria-current="page"' "$work_dir/admin"
grep -q 'data-widget-options="eclipse"' "$work_dir/admin"
grep -q 'data-widget-options="real-lunar-eclipse"' "$work_dir/admin"
grep -q 'data-widget-options="real-solar-eclipse"' "$work_dir/admin"
grep -q 'data-widget-options="solar-space-eclipse"' "$work_dir/admin"
grep -q 'Eclipse solar desde el espacio' "$work_dir/admin"

echo 'lunar embeds HTTP: ok'
