<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/real-eclipse-embeds.php';
function realEclipseAssert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function realEclipseFiniteTree(mixed $value):bool{if(is_float($value)||is_int($value))return is_finite((float)$value);if(is_array($value)){foreach($value as $item)if(!realEclipseFiniteTree($item))return false;}return true;}
$lunarInstance=realEclipseInstance(['date'=>'2026-03-03','lat'=>'-34.6037','lon'=>'-58.3816']);
$lunar=realLunarEclipsePayload($lunarInstance,realLunarEclipseOptions([]));
$lunarDefaults=realLunarEclipseOptions([]);
realEclipseAssert($lunarDefaults['totality_brightness']===0.55&&$lunarDefaults['totality_copper_intensity']===0.7,'Cambió el tratamiento perceptual inicial de totalidad.');
realEclipseAssert($lunarDefaults['totality_max_darkness']===0.88&&$lunarDefaults['totality_gradient_contrast']===1.25&&$lunarDefaults['totality_edge_color']==='#d98b45'&&$lunarDefaults['totality_deep_color']==='#5a120e','Cambió el gradiente umbral predeterminado.');
realEclipseAssert($lunarDefaults['totality_saturation']===1.1&&$lunarDefaults['totality_texture_contrast']===0.58&&$lunarDefaults['totality_gradient_softness']===0.16&&$lunarDefaults['totality_atmospheric_irregularity']===0.1,'Cambió el tratamiento espacial predeterminado de totalidad.');
realEclipseAssert($lunarDefaults['sky_brightness']===0.0&&$lunarDefaults['sky_color']==='#02040a','Cambió el cielo predeterminado del eclipse lunar real.');
$lunarSkyOptions=realLunarEclipseOptions(['sky_brightness'=>'1.25','sky_color'=>'#18284A']);
realEclipseAssert($lunarSkyOptions['sky_brightness']===1.25&&$lunarSkyOptions['sky_color']==='#18284a','No se validan los controles del cielo lunar.');
$lunarTotalityOptions=realLunarEclipseOptions(['totality_brightness'=>'1.2','totality_copper_intensity'=>'1.5']);
realEclipseAssert($lunarTotalityOptions['totality_brightness']===1.2&&$lunarTotalityOptions['totality_copper_intensity']===1.5,'No se validan los parámetros exclusivos de totalidad.');
$lunarGradientOptions=realLunarEclipseOptions(['totality_max_darkness'=>'0.93','totality_gradient_contrast'=>'1.8','totality_edge_color'=>'#E09A52','totality_deep_color'=>'#410807','totality_saturation'=>'1.4','totality_texture_contrast'=>'0.45','totality_gradient_softness'=>'0.22','totality_atmospheric_irregularity'=>'0']);
realEclipseAssert($lunarGradientOptions['totality_max_darkness']===0.93&&$lunarGradientOptions['totality_gradient_contrast']===1.8&&$lunarGradientOptions['totality_edge_color']==='#e09a52'&&$lunarGradientOptions['totality_deep_color']==='#410807','No se normalizan oscuridad, contraste o tonos del gradiente umbral.');
realEclipseAssert($lunarGradientOptions['totality_saturation']===1.4&&$lunarGradientOptions['totality_texture_contrast']===0.45&&$lunarGradientOptions['totality_gradient_softness']===0.22&&$lunarGradientOptions['totality_atmospheric_irregularity']===0.0,'No se normalizan textura, suavidad o irregularidad de totalidad.');
realEclipseAssert($lunar['eclipse']['classification']==='total','No seleccionó el eclipse lunar real solicitado.');
realEclipseAssert(count($lunar['eclipse']['samples'])===181,'La serie lunar no tiene 181 muestras.');
realEclipseAssert(isset($lunar['eclipse']['contacts']['P1'],$lunar['eclipse']['contacts']['P4']),'Faltan contactos lunares reales.');
realEclipseAssert(isset($lunar['eclipse']['samples'][90]['moon']['disk_angle']),'Falta orientación aparente lunar.');
realEclipseAssert(realEclipseFiniteTree($lunar['eclipse']['samples']),'La serie lunar contiene NaN o Infinity.');
realEclipseAssert($lunar['eclipse']['timezone']==='America/Argentina/Buenos_Aires','La zona horaria no se resolvió desde coordenadas.');
$augustLunar=realLunarEclipsePayload(realEclipseInstance(['date'=>'2026-08-28','lat'=>'-34.6037','lon'=>'-58.3816','elevation'=>'0']),realLunarEclipseOptions([]));
realEclipseAssert(count($augustLunar['eclipse']['samples'])===181&&realEclipseFiniteTree($augustLunar['eclipse']['samples']),'El eclipse lunar del 28/08/2026 no produce una serie renderizable.');
$solarInstance=realEclipseInstance(['date'=>'2026-08-12','lat'=>'43.3623','lon'=>'-8.4115']);
$solarDefaults=realSolarEclipseOptions([]);
realEclipseAssert($solarDefaults['corona_level']===7.0&&$solarDefaults['prominence_level']===4.0&&$solarDefaults['baily_level']===6.0,'Cambió el contrato visual solar inicial.');
realEclipseAssert($solarDefaults['exposure']===1.0&&$solarDefaults['sun_intensity']===1.0&&$solarDefaults['limb_darkening']===0.075,'Faltan los ajustes generales de fotosfera.');
realEclipseAssert($solarDefaults['sky_brightness']===1.0&&$solarDefaults['corona_intensity']===1.0&&$solarDefaults['prominence_intensity']===1.0&&$solarDefaults['baily_intensity']===1.0,'Faltan intensidades independientes del render solar.');
realEclipseAssert($solarDefaults['totality_effects_before_seconds']===5.0&&$solarDefaults['totality_effects_after_seconds']===5.0,'Cambió la ventana predeterminada de efectos de totalidad.');
$solarEffectWindow=realSolarEclipseOptions(['totality_effects_before_seconds'=>'12','totality_effects_after_seconds'=>'8']);
realEclipseAssert($solarEffectWindow['totality_effects_before_seconds']===12.0&&$solarEffectWindow['totality_effects_after_seconds']===8.0,'No se validan los márgenes temporales de efectos de totalidad.');
$solarAppearance=realSolarEclipseOptions(['exposure'=>'1.4','sun_intensity'=>'1.2','limb_darkening'=>'0.12','moon_color'=>'#020205','sky_brightness'=>'0.8','sky_color'=>'#102040','corona_brightness'=>'1.3','corona_color'=>'#d0e4ff','prominence_intensity'=>'0.7','prominence_color'=>'#ff402c','baily_intensity'=>'1.5','baily_color'=>'#fff0c0']);
realEclipseAssert($solarAppearance['exposure']===1.4&&$solarAppearance['limb_darkening']===0.12&&$solarAppearance['corona_intensity']===1.3&&$solarAppearance['baily_intensity']===1.5,'No se normalizan las intensidades visuales solares.');
realEclipseAssert($solarAppearance['moon_color']==='#020205'&&$solarAppearance['sky_color']==='#102040'&&$solarAppearance['corona_color']==='#d0e4ff'&&$solarAppearance['prominence_color']==='#ff402c'&&$solarAppearance['baily_color']==='#fff0c0','No se normalizan los colores solares configurables.');
$solarLevels=realSolarEclipseOptions(['corona_level'=>'10','prominence_level'=>'5','baily_level'=>'0']);
realEclipseAssert($solarLevels['corona_level']===10.0&&$solarLevels['prominence_level']===5.0&&$solarLevels['baily_level']===0.0,'No se validan los niveles visuales 0–10.');
$legacyVisuals=realSolarEclipseOptions(['corona'=>'1','prominences'=>'0','baily'=>'1','corona_intensity'=>'1.2']);
realEclipseAssert($legacyVisuals['corona_level']===6.0&&$legacyVisuals['prominence_level']===0.0&&$legacyVisuals['baily_level']===7.0,'Las URLs booleanas anteriores no se migran a niveles razonables.');
$solar=realSolarEclipsePayload($solarInstance,$solarDefaults);
realEclipseAssert(count($solar['eclipse']['samples'])===241,'La serie solar no tiene 241 muestras.');
realEclipseAssert(isset($solar['eclipse']['contacts']['C1'],$solar['eclipse']['contacts']['C4']),'Faltan contactos solares locales.');
realEclipseAssert(is_float($solar['eclipse']['samples'][120]['moon_radius_solar_radii']),'Falta el tamaño topocéntrico relativo.');
realEclipseAssert(isset($solar['eclipse']['samples'][120]['celestial_north_screen_angle']),'Falta orientación aparente solar.');
realEclipseAssert(str_contains($solar['visual_note'],'representaciones visuales'),'No se declara la separación de capas visuales.');
realEclipseAssert(!isset($solar['eclipse']['animation']['corona'],$solar['eclipse']['animation']['prominences'],$solar['eclipse']['animation']['baily']),'El payload nuevo conserva booleanos visuales ambiguos.');
$none=realSolarEclipsePayload(realEclipseInstance(['date'=>'2026-08-12','lat'=>'-34.6037','lon'=>'-58.3816']),realSolarEclipseOptions([]));
realEclipseAssert($none['eclipse']['visible']===false&&$none['eclipse']['local_classification']===null,'Una ubicación fuera del eclipse no conserva el resultado local real.');
$spaceDefaults=realSolarSpaceEclipseOptions([]);
realEclipseAssert($spaceDefaults['show_moon']===true&&$spaceDefaults['show_penumbra']===true&&$spaceDefaults['show_core']===true&&$spaceDefaults['show_terminator']===true,'Cambió la visibilidad inicial de la escena espacial.');
realEclipseAssert($spaceDefaults['distance_scale']===3.4&&$spaceDefaults['rotation']==='free'&&$spaceDefaults['follow_shadow']===false,'Cambió la composición inicial de la escena espacial.');
$spaceOptions=realSolarSpaceEclipseOptions(['show_moon'=>'0','penumbra_opacity'=>'0.35','core_opacity'=>'0.8','distance_scale'=>'5','rotation'=>'locked','follow_shadow'=>'1']);
realEclipseAssert($spaceOptions['show_moon']===false&&$spaceOptions['penumbra_opacity']===0.35&&$spaceOptions['core_opacity']===0.8&&$spaceOptions['distance_scale']===5.0&&$spaceOptions['rotation']==='locked'&&$spaceOptions['follow_shadow']===true,'No se validan las opciones del eclipse visto desde el espacio.');
$spaceTotal=realSolarSpaceEclipsePayload(realEclipseInstance(['date'=>'2026-08-12']),$spaceDefaults);
realEclipseAssert(count($spaceTotal['eclipse']['samples'])===181&&realEclipseFiniteTree($spaceTotal['eclipse']['samples']),'La escena espacial total no entrega 181 muestras finitas.');
realEclipseAssert(isset($spaceTotal['eclipse']['contacts']['C1'],$spaceTotal['eclipse']['contacts']['C2'],$spaceTotal['eclipse']['contacts']['C3'],$spaceTotal['eclipse']['contacts']['C4']),'La escena espacial total no deriva sus contactos globales desde los conos.');
$spaceSamples=$spaceTotal['eclipse']['samples'];
$spaceNorm=static fn(array $v):float=>sqrt($v['x']**2+$v['y']**2+$v['z']**2);
$spaceCompressed=[];
foreach([0,30,60,90,120,150,180] as $sampleIndex){$v=$spaceSamples[$sampleIndex]['moon_position_inertial_km'];$length=$spaceNorm($v);$spaceCompressed[]=[$v['x']/$length*$spaceDefaults['distance_scale'],$v['y']/$length*$spaceDefaults['distance_scale'],$v['z']/$length*$spaceDefaults['distance_scale']];}
foreach($spaceCompressed as $v)realEclipseAssert(abs(sqrt($v[0]**2+$v[1]**2+$v[2]**2)-$spaceDefaults['distance_scale'])<1e-12,'La compresión visual Luna–Tierra dejó de ser constante.');
$spaceSteps=[];for($i=1;$i<count($spaceCompressed);$i++)$spaceSteps[]=sqrt(($spaceCompressed[$i][0]-$spaceCompressed[$i-1][0])**2+($spaceCompressed[$i][1]-$spaceCompressed[$i-1][1])**2+($spaceCompressed[$i][2]-$spaceCompressed[$i-1][2])**2);
realEclipseAssert(max($spaceSteps)/min($spaceSteps)<1.08,'La trayectoria inercial igualmente espaciada presenta un cambio artificial de velocidad.');
$middleSample=$spaceSamples[90];$theta=deg2rad($middleSample['greenwich_sidereal_angle_degrees']);$inertial=$middleSample['moon_position_inertial_km'];$earthFixed=$middleSample['moon_position_earth_fixed_km'];
realEclipseAssert(abs(cos($theta)*$inertial['x']+sin($theta)*$inertial['y']-$earthFixed['x'])<1e-6&&abs(-sin($theta)*$inertial['x']+cos($theta)*$inertial['y']-$earthFixed['y'])<1e-6,'Los marcos inercial y terrestre no conservan la rotación sidérea esperada.');
$spaceMaximumGeometry=(new AstronomyEngine\SolarEclipseShadowGeometry())->calculate(new DateTimeImmutable($spaceTotal['eclipse']['maximum']));
realEclipseAssert($spaceMaximumGeometry['core_kind_at_earth_plane']==='umbra'&&$spaceMaximumGeometry['core_intersects_earth']===true,'El eclipse total no proyecta una umbra sobre la Tierra.');
$spaceAnnular=realSolarSpaceEclipsePayload(realEclipseInstance(['date'=>'2026-02-17']),$spaceDefaults);
$spaceAnnularGeometry=(new AstronomyEngine\SolarEclipseShadowGeometry())->calculate(new DateTimeImmutable($spaceAnnular['eclipse']['maximum']));
realEclipseAssert($spaceAnnular['eclipse']['classification']==='annular'&&$spaceAnnularGeometry['core_kind_at_earth_plane']==='antumbra','El eclipse anular no proyecta antumbra.');
$solarRenderer=file_get_contents(__DIR__.'/../assets/js/real-solar-eclipse-widget.js');
$spaceRenderer=file_get_contents(__DIR__.'/../assets/js/solar-eclipse-space-widget.js');
$admin=file_get_contents(__DIR__.'/../admin/widgets-lunares/index.php');
$adminModule=file_get_contents(__DIR__.'/../assets/js/lunar-widget-admin.js');
$timelineModule=file_get_contents(__DIR__.'/../assets/js/real-eclipse-controls.js');
$lunarRenderer=file_get_contents(__DIR__.'/../assets/js/real-lunar-eclipse-widget.js');
realEclipseAssert(is_string($solarRenderer)&&str_contains($solarRenderer,'paintFlatSun')&&str_contains($solarRenderer,'limbDarkening'),'El Sol no conserva el disco plano y el limb darkening configurable.');
realEclipseAssert(str_contains($solarRenderer,'bezierCurveTo')&&str_contains($solarRenderer,'paintCorona')&&!str_contains($solarRenderer,"for(let i=0;i<36"),'La corona no usa filamentos suaves o conserva la rueda anterior.');
realEclipseAssert(str_contains($solarRenderer,'coveredByMoon')&&str_contains($solarRenderer,'paintProminences'),'Las prominencias no están vinculadas al limbo oculto.');
realEclipseAssert(str_contains($solarRenderer,'totalityEffectReveal')&&str_contains($solarRenderer,'contactEffectReveal')&&!str_contains($solarRenderer,'smoothstep(3000, 22000, closestContact)'),'Los efectos solares no respetan las ventanas configurables alrededor de C2/C3.');
realEclipseAssert(is_string($admin)&&str_contains($admin,'data-option="corona_level"')&&str_contains($admin,'data-option="prominence_level"')&&str_contains($admin,'data-option="baily_level"'),'Administración no expone los tres niveles visuales.');
realEclipseAssert(str_contains($admin,'data-option="totality_effects_before_seconds"')&&str_contains($admin,'data-option="totality_effects_after_seconds"'),'Administración no expone los márgenes temporales de totalidad.');
realEclipseAssert(is_string($spaceRenderer)&&str_contains($spaceRenderer,'diskOverlap')&&str_contains($spaceRenderer,'eclipseSunPosition')&&str_contains($spaceRenderer,'eclipseMoonPosition'),'La sombra superficial espacial no deriva de los discos aparentes reales.');
realEclipseAssert(str_contains($spaceRenderer,'createFrustum')&&str_contains($spaceRenderer,"coreKind === 'antumbra'")&&str_contains($spaceRenderer,'Distancias no a escala')===false,'El renderer espacial no distingue los conos o contiene texto de presentación incorrectamente.');
realEclipseAssert(str_contains($spaceRenderer,'interpolateAtTime')&&str_contains($spaceRenderer,'moon_position_inertial_km')&&str_contains($spaceRenderer,'.normalize().multiplyScalar(Number(options.distance_scale))'),'La Luna espacial no sigue la cadena inercial → interpolación temporal → compresión constante.');
realEclipseAssert(str_contains($spaceRenderer,'earth.rotation.y')&&str_contains($spaceRenderer,'moonRelativePosition')&&!str_contains($spaceRenderer,'shadowPoint.clone().addScaledVector'),'La rotación terrestre sigue contaminando la trayectoria lunar o falta el diagnóstico de cámara fija.');
realEclipseAssert(str_contains($admin,'data-widget-options="solar-space-eclipse"')&&str_contains($admin,'data-option="penumbra_opacity"')&&str_contains($admin,'data-option="follow_shadow"'),'Administración no integra el eclipse solar desde el espacio.');
realEclipseAssert(str_contains($admin,'data-option="exposure"')&&str_contains($admin,'data-option="sun_intensity"')&&str_contains($admin,'data-option="corona_brightness"')&&str_contains($admin,'data-option="baily_color"'),'Administración no expone los ajustes finos solares.');
realEclipseAssert(is_string($adminModule)&&str_contains($adminModule,"previewParameters.set('_preview_progress'")&&str_contains($adminModule,'dataset.eclipseProgress'),'La preview no preserva el instante al cambiar ajustes.');
realEclipseAssert(str_contains($adminModule,'const importUrl = () =>')&&str_contains($adminModule,'parsed.pathname.endsWith(`/embeds/${definition.filename}`)')&&str_contains($adminModule,'control.value = value'),'El generador no importa parámetros desde URL para todos los widgets.');
realEclipseAssert(str_contains($adminModule,"aquellas-lunas:lunar-widget-builder:v1")&&str_contains($adminModule,'localStorage.setItem')&&str_contains($adminModule,'restoreState();'),'El generador no conserva o restaura su última configuración tras F5.');
realEclipseAssert(is_string($timelineModule)&&str_contains($timelineModule,"get('_preview_progress')")&&str_contains($timelineModule,'root.dataset.eclipseProgress'),'El widget no restaura o publica el progreso de preview.');
realEclipseAssert(str_contains($timelineModule,'interpolateValue')&&str_contains($timelineModule,"typeof a === 'object'"),'La interpolación no recorre la geometría lunar anidada.');
realEclipseAssert(str_contains($timelineModule,'interpolateAngleDegrees')&&str_contains($timelineModule,"'celestial_north_screen_angle'")&&str_contains($timelineModule,"'disk_angle'"),'La interpolación no trata la envoltura angular común de ambos eclipses.');
realEclipseAssert(str_contains($timelineModule,'unwrapAngularSamples')&&str_contains($lunarRenderer,'interpolate(samples, progress)')&&str_contains($solarRenderer,'interpolate(samples, progress)'),'Los renderers reales no consumen series angulares continuas.');
realEclipseAssert(str_contains($lunarRenderer,"real-eclipse-controls.js?v=20260827-infographic-capture")&&str_contains($solarRenderer,"real-eclipse-controls.js?v=20260827-infographic-capture"),'La dependencia compartida de timeline y captura puede quedar desactualizada en caché.');
$shortestAngularDelta=static fn(float $first,float $second):float=>fmod(fmod($second-$first+540.0,360.0)+360.0,360.0)-180.0;
realEclipseAssert(abs($shortestAngularDelta(359.4,0.6)-1.2)<1e-9&&abs($shortestAngularDelta(-179.5,179.5)+1.0)<1e-9,'La interpolación angular de prueba no elige el arco corto.');
realEclipseAssert(is_string($lunarRenderer)&&str_contains($lunarRenderer,'const moonGeometry = sample.moon || {}')&&!str_contains($lunarRenderer,'sample.disk_angle'),'El renderer lunar vuelve a leer la orientación fuera de sample.moon.');
realEclipseAssert(str_contains($lunarRenderer,'const cameraDistance = 5.2')&&str_contains($lunarRenderer,'cameraDistance / Math.min(1, camera.aspect)')&&str_contains($lunarRenderer,"renderer.domElement.className = 'real-eclipse-widget__canvas'"),'El eclipse lunar real no conserva el encuadre seguro o el tamaño CSS independiente del DPR.');
realEclipseAssert(str_contains($lunarRenderer,'Number.isFinite')&&str_contains($lunarRenderer,'configureTexture'),'El renderer lunar no protege matrices finitas o no replica la preparación de texturas didáctica.');
realEclipseAssert(str_contains($lunarRenderer,'gl_FragColor=vec4(outgoingLight,diffuseColor.a)')&&!str_contains($lunarRenderer,'THREE.ShaderChunk.opaque_fragment'),'El shader lunar vuelve a insertar un chunk GLSL después de la expansión de includes.');
realEclipseAssert(str_contains($lunarRenderer,'totalityFactor')&&str_contains($lunarRenderer,'smoothstep(u2, maximum, timestamp)')&&str_contains($lunarRenderer,'1 - smoothstep(maximum, u3, timestamp)'),'La adaptación de totalidad no tiene una envolvente continua U2–máximo–U3.');
realEclipseAssert(str_contains($lunarRenderer,'rawDepth')&&str_contains($lunarRenderer,'distance(vDisk,shadowCenter)')&&str_contains($lunarRenderer,'totalityIrregularity'),'El shader de totalidad no deriva brillo y color de la profundidad umbral real.');
realEclipseAssert(str_contains($lunarRenderer,'eclipse.animation.sky_color')&&str_contains($lunarRenderer,'eclipse.animation.sky_brightness')&&str_contains($lunarRenderer,'renderer.setClearColor(skyColor, Math.min(1, skyBrightness))'),'El renderer lunar no aplica color y luminosidad configurables al cielo.');
realEclipseAssert(str_contains($admin,'data-option="sky_brightness"')&&str_contains($admin,'data-option="sky_color"'),'Administración no expone color y luminosidad del cielo lunar.');
realEclipseAssert(str_contains($admin,'data-option="totality_brightness"')&&str_contains($admin,'data-option="totality_copper_intensity"'),'Administración no expone los ajustes perceptuales de totalidad.');
foreach(['totality_max_darkness','totality_gradient_contrast','totality_edge_color','totality_deep_color','totality_saturation','totality_texture_contrast','totality_gradient_softness','totality_atmospheric_irregularity'] as $totalityOption)realEclipseAssert(str_contains($admin,'data-option="'.$totalityOption.'"'),'Falta el control de totalidad '.$totalityOption.'.');
echo "real-eclipse-embeds: OK\n";
