<?php

declare(strict_types=1);

$variable = static function (
    string $key, string $name, string $shortName, string $category, string $description,
    string $unit, string $scaleGroup, string $scope, string $provider, array $dependencies,
    int $precision, int $order, string $type = 'number'
): array {
    return compact('key', 'name', 'shortName', 'category', 'description', 'type', 'unit',
        'scaleGroup', 'scope', 'provider', 'dependencies', 'precision', 'order');
};
$extrema = static function (array $definition, string $label, int $minimumYears, int $recommendedYears,
    string $maximumLabel, string $minimumLabel): array {
    return $definition + ['extrema_supported' => true, 'extrema_label' => $label,
        'extrema_minimum_years' => $minimumYears, 'extrema_recommended_years' => $recommendedYears,
        'extrema_maximum_label' => $maximumLabel, 'extrema_minimum_label' => $minimumLabel];
};
$circular = static fn(array $definition): array => $definition + [
    'phase_supported' => true, 'relation_supported' => true, 'extrema_supported' => false,
    'circular_period' => 360,
];

return [
    'moon_illumination' => $variable('moon_illumination', 'Iluminación lunar', 'Iluminación', 'Luna', 'Fracción iluminada del disco lunar a las 00:00 locales.', '%', 'percent', 'global', 'moon_instant', [], 4, 10),
    'moon_phase_angle' => $variable('moon_phase_angle', 'Ángulo de fase lunar', 'Ángulo de fase', 'Ciclos y geometría', 'Ángulo Sol-Luna derivado de la fracción iluminada; 0° en Luna llena y 180° en Luna nueva.', '°', 'angle', 'global', 'moon_instant', [], 4, 20),
    'moon_distance_geocentric' => $extrema($variable('moon_distance_geocentric', 'Distancia lunar geocéntrica', 'Distancia geocéntrica', 'Luna', 'Distancia desde el centro de la Tierra a las 00:00 locales.', 'km', 'distance', 'global', 'moon_instant', [], 2, 30), 'Distancia lunar geocéntrica', 2, 5, 'Apogeos diarios', 'Perigeos diarios'),
    'moon_distance_topocentric' => $extrema($variable('moon_distance_topocentric', 'Distancia lunar topocéntrica', 'Distancia topocéntrica', 'Observación local', 'Distancia desde el observador a las 00:00 locales.', 'km', 'distance', 'local', 'moon_instant', [], 2, 40), 'Distancia lunar topocéntrica', 2, 5, 'Máximos diarios de distancia topocéntrica', 'Mínimos diarios de distancia topocéntrica'),
    'moon_ecliptic_latitude' => $variable('moon_ecliptic_latitude', 'Latitud eclíptica lunar', 'Latitud eclíptica', 'Ciclos y geometría', 'Latitud eclíptica geocéntrica a las 00:00 locales.', '°', 'angle_signed', 'global', 'moon_instant', [], 4, 50),
    'moon_ecliptic_longitude' => $circular($variable('moon_ecliptic_longitude', 'Longitud eclíptica lunar', 'Longitud eclíptica lunar', 'Ciclos y geometría', 'Longitud eclíptica geocéntrica aparente, referida al equinoccio verdadero de fecha, a las 00:00 locales.', '°', 'ecliptic_cycle_angle', 'global', 'moon_instant', [], 4, 51)),
    'moon_node_angle' => $circular($variable('moon_node_angle', 'Ángulo Luna–nodo', 'Ángulo Luna–nodo', 'Ciclos y geometría', 'Argumento medio de latitud lunar. Indica la posición de la Luna dentro de su ciclo respecto de los nodos de su órbita. Cerca de 0° cruza el nodo ascendente y cerca de 180° el descendente.', '°', 'ecliptic_cycle_angle', 'global', 'moon_instant', [], 4, 52)),
    'moon_mean_ascending_node_longitude' => $circular($variable('moon_mean_ascending_node_longitude', 'Longitud del nodo ascendente medio', 'Nodo ascendente medio', 'Ciclos y geometría', 'Longitud eclíptica del nodo ascendente medio de la órbita lunar, referida al equinoccio medio de fecha, a las 00:00 locales.', '°', 'ecliptic_cycle_angle', 'global', 'moon_instant', [], 4, 53)),
    'moon_right_ascension' => $variable('moon_right_ascension', 'Ascensión recta lunar', 'Ascensión recta', 'Ciclos y geometría', 'Ascensión recta geocéntrica a las 00:00 locales.', 'h', 'hours_angle', 'global', 'moon_instant', [], 5, 60),
    'moon_declination' => $variable('moon_declination', 'Declinación lunar', 'Declinación', 'Ciclos y geometría', 'Declinación geocéntrica a las 00:00 locales.', '°', 'angle_signed', 'global', 'moon_instant', [], 4, 70),
    'moon_altitude' => $variable('moon_altitude', 'Altura lunar', 'Altura lunar', 'Observación local', 'Altura topocéntrica sin refracción a las 00:00 locales.', '°', 'altitude', 'local', 'moon_instant', [], 4, 80),
    'moon_azimuth' => $variable('moon_azimuth', 'Azimut lunar', 'Azimut lunar', 'Observación local', 'Azimut topocéntrico a las 00:00 locales.', '°', 'azimuth', 'local', 'moon_instant', [], 4, 90),
    'sun_moon_angular_distance' => $variable('sun_moon_angular_distance', 'Distancia angular Sol–Luna', 'Distancia angular Sol–Luna', 'Ciclos y geometría', 'Separación angular geocéntrica entre las direcciones al Sol y a la Luna a las 00:00 locales; también llamada elongación Sol–Luna.', '°', 'angular_separation', 'global', 'moon_instant', [], 3, 100),
    'moon_apparent_diameter_arcmin' => $variable('moon_apparent_diameter_arcmin', 'Diámetro aparente de la Luna', 'Diámetro aparente de la Luna', 'Luna', 'Diámetro angular geocéntrico del disco lunar a las 00:00 locales, derivado de la distancia al centro de la Tierra.', 'min de arco', 'lunar_angular_diameter', 'global', 'moon_instant', [], 3, 105),
    'sun_altitude' => $variable('sun_altitude', 'Altura solar', 'Altura solar', 'Sol', 'Altura topocéntrica sin refracción a las 00:00 locales.', '°', 'altitude', 'local', 'sun_instant', [], 4, 110),
    'sun_azimuth' => $variable('sun_azimuth', 'Azimut solar', 'Azimut solar', 'Sol', 'Azimut topocéntrico a las 00:00 locales.', '°', 'azimuth', 'local', 'sun_instant', [], 4, 120),
    'sun_distance_km' => $variable('sun_distance_km', 'Distancia Tierra–Sol', 'Distancia Tierra–Sol', 'Sol', 'Distancia entre el centro de la Tierra y el Sol en la fecha indicada.', 'km', 'solar_distance', 'global', 'sun_instant', [], 0, 130),
    'sun_equation_of_time_minutes' => $variable('sun_equation_of_time_minutes', 'Ecuación del tiempo', 'Ecuación del tiempo', 'Sol', 'Tiempo solar aparente menos tiempo solar medio a las 00:00 locales. Un valor positivo indica que el reloj solar está adelantado respecto del tiempo solar medio; uno negativo, atrasado.', 'min', 'equation_of_time', 'global', 'sun_instant', [], 3, 140),
    'sun_node_angle' => $circular($variable('sun_node_angle', 'Ángulo Sol–nodo', 'Ángulo Sol–nodo', 'Ciclos y geometría', 'Diferencia entre la longitud eclíptica aparente del Sol y el nodo ascendente medio lunar. Cuando se acerca a 0° o 180° se abre aproximadamente una temporada de eclipses.', '°', 'ecliptic_cycle_angle', 'global', 'sun_instant', [], 4, 141)),
    'moonrise_time' => $variable('moonrise_time', 'Hora de salida lunar', 'Salida lunar', 'Luna', 'Hora local decimal de la primera salida lunar del día.', 'hora local', 'local_time', 'local', 'moon_events', [], 4, 210),
    'moonset_time' => $variable('moonset_time', 'Hora de puesta lunar', 'Puesta lunar', 'Luna', 'Hora local decimal de la primera puesta lunar del día.', 'hora local', 'local_time', 'local', 'moon_events', [], 4, 220),
    'moonrise_azimuth' => $variable('moonrise_azimuth', 'Azimut de salida lunar', 'Azimut salida lunar', 'Observación local', 'Azimut lunar calculado en el instante de salida.', '°', 'azimuth', 'local', 'moon_events', [], 3, 230),
    'moonset_azimuth' => $variable('moonset_azimuth', 'Azimut de puesta lunar', 'Azimut puesta lunar', 'Observación local', 'Azimut lunar calculado en el instante de puesta.', '°', 'azimuth', 'local', 'moon_events', [], 3, 240),
    'moon_above_horizon_hours' => $extrema($variable('moon_above_horizon_hours', 'Tiempo lunar sobre el horizonte', 'Luna visible', 'Observación local', 'Suma de los intervalos de visibilidad del contrato lunar diario.', 'h', 'duration', 'local', 'moon_events', [], 4, 250), 'Tiempo lunar sobre el horizonte', 2, 5, 'Máximos locales de tiempo sobre el horizonte', 'Mínimos locales de tiempo sobre el horizonte'),
    'sunrise_time' => $variable('sunrise_time', 'Hora de salida solar', 'Salida solar', 'Sol', 'Hora local decimal de la salida solar.', 'hora local', 'local_time', 'local', 'sun_events', [], 4, 310),
    'sunset_time' => $variable('sunset_time', 'Hora de puesta solar', 'Puesta solar', 'Sol', 'Hora local decimal de la puesta solar.', 'hora local', 'local_time', 'local', 'sun_events', [], 4, 320),
    'sunrise_azimuth' => $variable('sunrise_azimuth', 'Azimut de salida solar', 'Azimut salida solar', 'Observación local', 'Azimut solar calculado en el instante de salida.', '°', 'azimuth', 'local', 'sun_events', [], 3, 330),
    'sunset_azimuth' => $variable('sunset_azimuth', 'Azimut de puesta solar', 'Azimut puesta solar', 'Observación local', 'Azimut solar calculado en el instante de puesta.', '°', 'azimuth', 'local', 'sun_events', [], 3, 340),
    'daylight_hours' => $extrema($variable('daylight_hours', 'Duración del día', 'Duración del día', 'Sol', 'Tiempo del día civil con el Sol sobre el horizonte convencional.', 'h', 'duration', 'local', 'sun_events', [], 4, 350), 'Duración del día', 5, 10, 'Máximos locales de duración del día', 'Mínimos locales de duración del día'),
    'night_hours' => $extrema($variable('night_hours', 'Duración de la noche', 'Duración de la noche', 'Observación local', 'Duración del día civil menos el tiempo con el Sol sobre el horizonte.', 'h', 'duration', 'local', 'sun_events', [], 4, 360), 'Duración de la noche', 5, 10, 'Máximos locales de duración de la noche', 'Mínimos locales de duración de la noche'),
    'moonrise_amplitude' => $extrema($variable('moonrise_amplitude', 'Amplitud de salida lunar', 'Amplitud salida lunar', 'Ciclos y geometría', 'Desplazamiento angular respecto del este: 90° menos azimut; positivo hacia el norte.', '°', 'amplitude', 'local', 'derived', ['moonrise_azimuth'], 3, 410), 'Amplitud de salida lunar', 2, 5, 'Máximos locales de amplitud de salida lunar', 'Mínimos locales de amplitud de salida lunar'),
    'moonset_amplitude' => $extrema($variable('moonset_amplitude', 'Amplitud de puesta lunar', 'Amplitud puesta lunar', 'Ciclos y geometría', 'Desplazamiento angular respecto del oeste: azimut menos 270°; positivo hacia el norte.', '°', 'amplitude', 'local', 'derived', ['moonset_azimuth'], 3, 420), 'Amplitud de puesta lunar', 2, 5, 'Máximos locales de amplitud de puesta lunar', 'Mínimos locales de amplitud de puesta lunar'),
    'sunrise_amplitude' => $extrema($variable('sunrise_amplitude', 'Amplitud de salida solar', 'Amplitud salida solar', 'Ciclos y geometría', 'Desplazamiento angular respecto del este: 90° menos azimut; positivo hacia el norte.', '°', 'amplitude', 'local', 'derived', ['sunrise_azimuth'], 3, 430), 'Amplitud de salida solar', 5, 10, 'Máximos locales de amplitud de salida solar', 'Mínimos locales de amplitud de salida solar'),
    'sunset_amplitude' => $extrema($variable('sunset_amplitude', 'Amplitud de puesta solar', 'Amplitud puesta solar', 'Ciclos y geometría', 'Desplazamiento angular respecto del oeste: azimut menos 270°; positivo hacia el norte.', '°', 'amplitude', 'local', 'derived', ['sunset_azimuth'], 3, 440), 'Amplitud de puesta solar', 5, 10, 'Máximos locales de amplitud de puesta solar', 'Mínimos locales de amplitud de puesta solar'),
    'moonrise_daily_difference' => $extrema($variable('moonrise_daily_difference', 'Diferencia diaria de salida lunar', 'Δ salida lunar', 'Ciclos y geometría', 'Minutos de adelanto o retraso frente al día civil anterior; positivo significa más tarde.', 'min', 'time_difference', 'local', 'derived', ['moonrise_time'], 2, 450), 'Diferencia diaria de salida lunar', 2, 5, 'Máximos locales de diferencia de salida lunar', 'Mínimos locales de diferencia de salida lunar'),
    'moonset_daily_difference' => $extrema($variable('moonset_daily_difference', 'Diferencia diaria de puesta lunar', 'Δ puesta lunar', 'Ciclos y geometría', 'Minutos de adelanto o retraso frente al día civil anterior; positivo significa más tarde.', 'min', 'time_difference', 'local', 'derived', ['moonset_time'], 2, 460), 'Diferencia diaria de puesta lunar', 2, 5, 'Máximos locales de diferencia de puesta lunar', 'Mínimos locales de diferencia de puesta lunar'),
    'sunrise_daily_difference' => $extrema($variable('sunrise_daily_difference', 'Diferencia diaria de salida solar', 'Δ salida solar', 'Ciclos y geometría', 'Minutos de adelanto o retraso frente al día civil anterior; positivo significa más tarde.', 'min', 'time_difference', 'local', 'derived', ['sunrise_time'], 2, 470), 'Diferencia diaria de salida solar', 5, 10, 'Máximos locales de diferencia de salida solar', 'Mínimos locales de diferencia de salida solar'),
    'sunset_daily_difference' => $extrema($variable('sunset_daily_difference', 'Diferencia diaria de puesta solar', 'Δ puesta solar', 'Ciclos y geometría', 'Minutos de adelanto o retraso frente al día civil anterior; positivo significa más tarde.', 'min', 'time_difference', 'local', 'derived', ['sunset_time'], 2, 480), 'Diferencia diaria de puesta solar', 5, 10, 'Máximos locales de diferencia de puesta solar', 'Mínimos locales de diferencia de puesta solar'),
];
